// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserSettings = `-- name: GetUserSettings :one
SELECT level, onboarding_completed_at
FROM users
WHERE id = $1
`

type GetUserSettingsRow struct {
	Level                 string             `json:"level"`
	OnboardingCompletedAt pgtype.Timestamptz `json:"onboarding_completed_at"`
}

func (q *Queries) GetUserSettings(ctx context.Context, id pgtype.UUID) (GetUserSettingsRow, error) {
	row := q.db.QueryRow(ctx, getUserSettings, id)
	var i GetUserSettingsRow
	err := row.Scan(&i.Level, &i.OnboardingCompletedAt)
	return i, err
}

const listActiveTopics = `-- name: ListActiveTopics :many
SELECT id, name
FROM topics
WHERE active
ORDER BY name
`

type ListActiveTopicsRow struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) ListActiveTopics(ctx context.Context) ([]ListActiveTopicsRow, error) {
	rows, err := q.db.Query(ctx, listActiveTopics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveTopicsRow
	for rows.Next() {
		var i ListActiveTopicsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveUserSettings = `-- name: SaveUserSettings :one
UPDATE users
SET level = $2,
    onboarding_completed_at = COALESCE(onboarding_completed_at, now())
WHERE id = $1
RETURNING level, onboarding_completed_at
`

type SaveUserSettingsParams struct {
	ID    pgtype.UUID `json:"id"`
	Level string      `json:"level"`
}

type SaveUserSettingsRow struct {
	Level                 string             `json:"level"`
	OnboardingCompletedAt pgtype.Timestamptz `json:"onboarding_completed_at"`
}

// Onboarding, once completed, stays completed: a later Save never
// clears onboarding_completed_at.
func (q *Queries) SaveUserSettings(ctx context.Context, arg SaveUserSettingsParams) (SaveUserSettingsRow, error) {
	row := q.db.QueryRow(ctx, saveUserSettings, arg.ID, arg.Level)
	var i SaveUserSettingsRow
	err := row.Scan(&i.Level, &i.OnboardingCompletedAt)
	return i, err
}
